### ISSUE TITLE
Getting StackOverflowError

### ISSUE THREAD

**Issue by prasad2kin** [jprante/elasticsearch-aggregations#3]
ElasticSearch 2.1.1

Request:

GET /sample/data/_search
{
  "size": 0,
  "from": 0,
  "query": {
    "match_all": {}
  },
  "aggs": {
    "tree": {
      "path": {
        "field": "treefield",
        "separator": "/",
        "max_depth" : 1,
        "order": {"_term": "desc"}
      }
    }
  }
}

Response:
{
   "error": {
      "root_cause": [
         {
            "type": "stack_overflow_error",
            "reason": null
         }
      ],
      "type": "stack_overflow_error",
      "reason": null
   },
   "status": 500
}

Stacktrace:
java.lang.StackOverflowError
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:947)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:314)
        at com.fasterxml.jackson.core.util.JsonGeneratorDelegate.writeStartObject(JsonGeneratorDelegate.java:189)
        at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeStartObject(JsonXContentGenerator.java:73)
        at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:180)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:271)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)
        at org.xbib.elasticsearch.search.aggregations.path.InternalPath.doXContentInternal(InternalPath.java:291)

I tried increasing heap size to 1G, but still kept getting issue. Unfortunately, I can't give you my real data using which, I'm getting this error. But to say, there are 58K documents to be exact & field contains data in a array e.g.

treefield: [
"/1546#BSA/986#BCM/985#CFM/1320#F1M/807#GP IIb IIIa M/402#GP IIb IIIa A",
"/1546#BSA/986#BCM/1445#PAM/312#PAI",
"/965#CA/945#VA/1445#PAM/312#PAI",
"/15588#PT/8145#SPM/985#CFM/1320#F1M/807#GP IIb IIIa M/402#GP IIb IIIa A"
],

Could you please take a look?

**Comment by jprante** [comment]
This error is strange.

I can not reproduce it. A new test https://github.com/jprante/elasticsearch-aggregations/blob/master/src/integration-test/java/org/xbib/elasticsearch/plugin/aggregations/SimpleAggregationTest.java does not show any evidence.

I'd be glad to receive a minimal test case so I can reproduce the issue.

In 2.1.1.1 I added a conditional check that hopefully can abort such a loop condition better, but it is untested.

**Comment by prasad2kin** [comment]
Hey Jörg,

Thanks for quick response, and sorry I was quite in hurry when I posted this problem (didn't want to forget problem), I'll take your latest fix & retry, if I get the same problem, I'll prepare a testcase & will send to you, otherwise I'll inform you whether problem is solved or not.

-P.

**Comment by prasad2kin** [comment]
Hey Jörg,

I've tested 2.1.1.1, problem still exists. I've created 
[sample data](https://github.com/jprante/elasticsearch-aggregations/files/112349/test.zip). This file contains test.json which is data in _bulk format. Please use command:

> curl -XPOST localhost:9200/_bulk --data-binary "@test.json"

to create index "test" with data. Once done, use the query,

```
GET /test/data/_search
{
  "size": 0,
  "from": 0,
  "query": {
    "match_all": {}
  },
  "aggs": {
    "tree": {
      "path": {
        "field": "treefield",
        "separator": "/",
        "max_depth" : 1,
        "order": {"_term": "desc"}
      }
    }
  }
}
```

to see the error on elastic console.

Response you'll get is like:

```
{
   "error": {
      "root_cause": [
         {
            "type": "stack_overflow_error",
            "reason": null
         }
      ],
      "type": "stack_overflow_error",
      "reason": null
   },
   "status": 500
}
```

**Comment by jprante** [comment]
I could reproduce the error. 

The reason is that `treefield` is analyzed, spits out high cardinality of token ABCD (>54000!) and clement-tourriere uses recursion to walk through the buckets, and this is deadly, 50k elements are a lot on the stack. This can be optimized, i.e. expressed in a while loop. Thanks for the hint.

But, if you use the keyword analyzer, which I strongly recommend on all fields you ever want to aggregate, the chance is high you can succeed.

The error disappears with the following:

```
DELETE /test

PUT /test
{
    "index.analysis.analyzer.default.type" : "keyword"
}

curl -XPOST localhost:9200/_bulk --data-binary "@test.json" > /dev/null

POST /test/data/_search
{
  "size": 0,
  "from": 0,
  "query": {
    "match_all": {}
  },
  "aggs": {
    "tree": {
      "path": {
        "field": "treefield",
        "separator": "/",
        "max_depth" : 1,
        "order": {"_term": "desc"}
      }
    }
  }
}
```

**Comment by prasad2kin** [comment]
Thanks for the tip on "keyword" analyzer, although, it succeeds for "max_depth=1", it starts giving same problem for "max_depth=5" onward, certainly for -1.

I guess, bucket walk though logic will need change as you mentioned...
